### ISSUE TITLE
Catalog docs vs ABCD-J docs

### ISSUE THREAD

**Issue by tmheunis** [abcd-j/data-catalog#12]
While creating the user docs for the catalog in order to provide instructions for how users can contribute to the catalog, this question came up: should there be ABCD-J level docs, and should the catalog docs be a subset of that? Or should we keep the catalog docs to the catalog and leave other higher-level decisions for future consideration?

If we decide to do top-level docs, with catalog instructions forming a part of that, we should probably have a separate repo in the abcd-j org for that, and then the content of `user-docs` in the current repo should move there.

**Comment by jsheunis** [comment]
This has been resolved as follows in the past weeks:
- the catalog sources are located in the `catalog` subdirectory of this repo, which is where the data.abcd-j.de site is deployed from (not with github pages anymore)
- the documentation is located in `docs` subdirectory (which was previously used for the catalog sources), where github pages deploys docs to rdm.abcd-j.de (custom domain)
- the RDM docs are catalog-level at the moment and could include other RDM-related content in future (e.g. a "For developers" section that details how to update the catalog)
- ABCD-J project-level docs are currently considered too general to have, but might be added in future if the need arises
