### ISSUE TITLE
Update developer instructions in README

### ISSUE THREAD

**Issue by tmheunis** [abcd-j/data-catalog#18]
The developer instructions in this repo's readme for updating the catalog is incomplete, and maybe also outdated. I was able to update the catalog recently with the help of @jsheunis, but this information would be more useful if it is somewhere persistent. Perhaps we should also consider adding such instructions to the RDM docs at rdm.abcd-j.de, or do we only want to keep that user-focused? @mih @jsheunis what do you think?

**Comment by jsheunis** [comment]
Indeed, I need to add this content soon. I have some work in progress locally that I'll push when finished. I'll add all to the readme for now, but I think having a section for developers in the RDM docs is a good idea (I also mentioned it here: https://github.com/abcd-j/data-catalog/issues/12). Perhaps it should just have the lowest visibility/priority on the docs site so as not to distract standard users.

**Comment by mih** [comment]
I think it is fine to add that, and it will be interesting to some. It would be useful to make clear what the target audience for each doc item is.
