### ISSUE TITLE
Request data access button should not be shown for public dataset

### ISSUE THREAD

**Issue by tmheunis** [abcd-j/data-catalog#25]

**Comment by jsheunis** [comment]
Makes sense to me, yes.

There wouldn't be an easy way to determine automatically whether a dataset is available publicly. And in some cases some files of a dataset might be publicly available and others not, and for the latter one might still want to have the ability to display the "request access" button.

Therefore, I think the best option is to have an explicit flag, part of a dataset-level config, through which it can be specified to show or hide the "request access" button.

Currently, the buttons shows automatically if a request_access_url or request_access_email is available on the dataset object: https://github.com/abcd-j/data-catalog/blob/main/catalog/templates/dataset-template.html#L47-L48
