### ISSUE TITLE
Show shortened format for DOI and License, not full URL

### ISSUE THREAD

**Issue by tmheunis** [abcd-j/data-catalog#26]
Feedback from @mih:

![image](https://github.com/abcd-j/data-catalog/assets/11378509/5d2f0370-e123-4f27-b80a-5178a8a2076a)

- The license label should be "CC0", and the link should point to the URL shown.
- Similar nitpick for the DOI. The DOI is 10.12751/g-node.c9nk4y, and what is shown is the resolved URL

**Comment by jsheunis** [comment]
DOI can be handled in the catalog javascript, it is already done correctly for publication doi. I.e. no need to change catalog entry code.

The license format is already
```
{
   "name": "",
   "url": ""
}
```
and rendered as `<a href="license-url">license-name</a>` in the catalog, so this will have to be updated in catalog-generating code (for future cases) and catalog metadata (for current case).

**Comment by jsheunis** [comment]
Turns out the dataset doi is already handled, it's just that it doesn't account for the `www` because the url is typically `https://doi.org/` without the `www`

**Comment by jsheunis** [comment]
Plan is to fix both issues by fixing catalog metadata, and then introduce code functions or checks to fix future occurrences of new metadata entries

**Comment by tmheunis** [comment]
This has now been fixed in the ABCD-J catalog. @jsheunis should I keep the issue open?

**Comment by tmheunis** [comment]
I will close this, and we can reopen if the issue jumps out again.
