### ISSUE TITLE
Create config to allow hiding "Request access" button, and recreate EMA pilot entries

### ISSUE THREAD

**Issue by jsheunis** [abcd-j/data-catalog#30]
This relates to https://github.com/abcd-j/data-catalog/issues/25

The current catalog metadata has been updated to address this issue in https://github.com/abcd-j/data-catalog/pull/27. But this change will be erased if the metadata is for that dataset is ever regenerated without accounting for the button hiding in a sustainable way.

A new config file needs to be added to `inputs` that allows to specify `"include_access_request": false` . Likely a generic config file e.g. `dataset_config_hide_access_request.json`. Then the EMA Pilot catalog entry have to be regenerated with this config.

**Comment by tmheunis** [comment]
This has been added in this commit: https://github.com/abcd-j/data-catalog/commit/911488c373399e62bc36585aee1144ab63a68db8
