### ISSUE TITLE
LinkML dependency for validation?

### ISSUE THREAD

**Issue by jsheunis** [abcd-j/data-catalog#5]
There is an abcd-j dataset schema (https://github.com/abcd-j/schema) which is very close to describing the exact structure of the tabby files that users will supply to describe their datasets.

In principle, this means we could use LinkML for validation of the tabby records (after they've been loaded into json). This might or might not be useful, depending on the way in which metadata is supplied, as hand edited tabby tsv files or as json records that result from completing a (from-schema-generated) web form.

tbd

**Comment by tmheunis** [comment]
I think we can close this. According to my understanding, with `datalad-concepts` we are working towards a general "data distribution" schema and schema-driven tools for viewing and editing metadata, which use LinkML at some point in the process. So perhaps when that is in a practically usable state we can work LinkML into the process, but until then we already have the scripts to generate metadata items from tabby records.
